apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
spec:
  storageClassName: frontend
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

